import { z } from "zod";

export const quoteFormSchema = z.object({
  firstName: z.string().min(1, "First name is required"),
  lastName: z.string().min(1, "Last name is required"),
  dateOfBirth: z.string().min(1, "Date of birth is required"),
  maritalStatus: z.string().min(1, "Marital status is required"),
  gender: z.string().min(1, "Gender is required"),
  streetAddress: z.string().min(1, "Street address is required"),
  state: z.string().min(1, "State is required"),
  zipCode: z.string().min(1, "Zip code is required"),
  phoneNumber: z.string().min(1, "Phone number is required"),
  canReceiveTexts: z.string().optional(),
  emailAddress: z.string().email("Valid email is required"),
  driverLicenseNumber: z.string().min(1, "Driver license number is required"),
  socialSecurityNumber: z.string().optional(),

  additionalDriverFirstName: z.string().optional(),
  additionalDriverLastName: z.string().optional(),
  additionalDriverDOB: z.string().optional(),
  additionalDriverLicense: z.string().optional(),

  vinNumber: z.string().optional(),
  vehicleUse: z.string().optional(),
  estimatedAnnualMileage: z.string().optional(),

  occupation: z.string().optional(),
  militaryService: z.string().optional(),
  isStudent: z.string().optional(),
});

export type QuoteFormValues = z.infer<typeof quoteFormSchema>;

export const defaultQuoteValues: QuoteFormValues = {
  firstName: "",
  lastName: "",
  dateOfBirth: "",
  maritalStatus: "",
  gender: "",
  streetAddress: "",
  state: "",
  zipCode: "",
  phoneNumber: "",
  canReceiveTexts: "",
  emailAddress: "",
  driverLicenseNumber: "",
  socialSecurityNumber: "",
  additionalDriverFirstName: "",
  additionalDriverLastName: "",
  additionalDriverDOB: "",
  additionalDriverLicense: "",
  vinNumber: "",
  vehicleUse: "",
  estimatedAnnualMileage: "",
  occupation: "",
  militaryService: "",
  isStudent: "",
};

export const QUOTE_FIELD_LABELS: Record<keyof QuoteFormValues, string> = {
  firstName: "First Name",
  lastName: "Last Name",
  dateOfBirth: "Date of Birth",
  maritalStatus: "Marital Status",
  gender: "Gender",
  streetAddress: "Street Address",
  state: "State",
  zipCode: "Zip Code",
  phoneNumber: "Phone Number",
  canReceiveTexts: "Can Receive Texts",
  emailAddress: "Email Address",
  driverLicenseNumber: "Driver License Number",
  socialSecurityNumber: "Social Security Number",
  additionalDriverFirstName: "Additional Driver First Name",
  additionalDriverLastName: "Additional Driver Last Name",
  additionalDriverDOB: "Additional Driver Date of Birth",
  additionalDriverLicense: "Additional Driver License Number",
  vinNumber: "VIN Number",
  vehicleUse: "Vehicle Use",
  estimatedAnnualMileage: "Estimated Annual Mileage",
  occupation: "Occupation",
  militaryService: "Military Service",
  isStudent: "Student",
};

export const CONVERSATION_FLOW: Array<{ key: keyof QuoteFormValues; question: string }> = [
  { key: "firstName", question: "What is your first name?" },
  { key: "lastName", question: "What is your last name?" },
  { key: "dateOfBirth", question: "What is your date of birth? (MM/DD/YYYY)" },
  { key: "maritalStatus", question: "What is your marital status? (Single, Married, Separated, Divorced, or Widowed)" },
  { key: "gender", question: "What is your gender? (Female, Male, or Non-specified)" },
  { key: "streetAddress", question: "What is your street address?" },
  { key: "state", question: "What state do you live in?" },
  { key: "zipCode", question: "What is your zip code?" },
  { key: "phoneNumber", question: "What is your phone number?" },
  { key: "canReceiveTexts", question: "Can you receive text messages at that number? (Yes/No)" },
  { key: "emailAddress", question: "What is your email address?" },
  { key: "driverLicenseNumber", question: "What is your driver license number?" },
  { key: "socialSecurityNumber", question: "What is your social security number? (Optional — say 'skip' if you prefer not to share)" },
  { key: "vinNumber", question: "What is your vehicle's VIN number? (Say 'skip' if you don't have it)" },
  { key: "vehicleUse", question: "What is the primary use of your vehicle? (Commute, Pleasure, or Business)" },
  { key: "estimatedAnnualMileage", question: "What is your estimated annual mileage? (1-5K, 6-10K, 11-15K, or 15K+)" },
  { key: "occupation", question: "What is your occupation? (Optional — say 'skip' if you prefer)" },
  { key: "militaryService", question: "Do you have any military service? (Optional — say 'skip' if not applicable)" },
  { key: "isStudent", question: "Are you a student? (Yes/No, optional — say 'skip' if not applicable)" },
];

export const FIELD_NAME_MAP: Record<string, keyof QuoteFormValues> = {
  "first name": "firstName",
  "firstname": "firstName",
  "last name": "lastName",
  "lastname": "lastName",
  "date of birth": "dateOfBirth",
  "dob": "dateOfBirth",
  "birthday": "dateOfBirth",
  "marital status": "maritalStatus",
  "marital": "maritalStatus",
  "gender": "gender",
  "sex": "gender",
  "street address": "streetAddress",
  "address": "streetAddress",
  "state": "state",
  "zip code": "zipCode",
  "zip": "zipCode",
  "zipcode": "zipCode",
  "phone number": "phoneNumber",
  "phone": "phoneNumber",
  "cell": "phoneNumber",
  "text messages": "canReceiveTexts",
  "can receive texts": "canReceiveTexts",
  "email": "emailAddress",
  "email address": "emailAddress",
  "driver license": "driverLicenseNumber",
  "license number": "driverLicenseNumber",
  "dl number": "driverLicenseNumber",
  "ssn": "socialSecurityNumber",
  "social security": "socialSecurityNumber",
  "social security number": "socialSecurityNumber",
  "additional driver first name": "additionalDriverFirstName",
  "additional driver last name": "additionalDriverLastName",
  "additional driver dob": "additionalDriverDOB",
  "additional driver license": "additionalDriverLicense",
  "vin": "vinNumber",
  "vin number": "vinNumber",
  "vehicle use": "vehicleUse",
  "annual mileage": "estimatedAnnualMileage",
  "mileage": "estimatedAnnualMileage",
  "occupation": "occupation",
  "military": "militaryService",
  "military service": "militaryService",
  "student": "isStudent",
};
